from __future__ import annotations

from pathlib import Path
from typing import Protocol

from popbuster.catalog import Tape
from popbuster.config import AppConfig


class DisplayPort(Protocol):
    def show_boot(self, message: str) -> None: ...

    def show_idle(self) -> None: ...

    def show_bumper(self) -> None: ...

    def show_playing(self, tape: Tape, resumed: bool) -> None: ...

    def show_paused(self, tape: Tape) -> None: ...

    def show_status(self, message: str) -> None: ...

    def show_error(self, message: str) -> None: ...

    def show_settings(self, config: AppConfig, selected_index: int) -> None: ...


class VideoPort(Protocol):
    def load(self, path: Path) -> None: ...

    def play(self) -> None: ...

    def pause(self) -> None: ...

    def stop(self) -> None: ...

    def seek_ms(self, position_ms: int) -> None: ...

    def position_ms(self) -> int: ...
